Release notes - 21.10
sdnfv/openNetVM pull request #318
Opened 2022-01-21 01:12 UTC by twood02

Release notes from 2021

2022-01-21 03:03 UTC, catherinemeadows requested changes

2022-01-21 03:03 UTC, catherinemeadows commented on docs/Releases.md
> +
```suggestion
- [[308](https://github.com/sdnfv/openNetVM/pull/308)] Adds socket ID information to NF and manager logging print statements. 
```

2022-01-29 18:52 UTC, twood02 commented
This should be ready to merge @catherinemeadows . Then we can merge from develop to master

2022-01-30 20:51 UTC, catherinemeadows commented
@twood02 Merging is blocked still. Can you change your PR to develop?

2022-01-30 21:14 UTC, twood02 commented
> @twood02 Merging is blocked still. Can you change your PR to develop?

oof rookie mistake.  should be fixed now.

2022-01-30 21:20 UTC, catherinemeadows approved these changes

2022-01-30 23:04 UTC, dennisafa approved these changes

2022-01-31 17:22 UTC, merged