Scaling Example NF Updates
sdnfv/openNetVM pull request #321
Opened 2022-03-17 15:39 UTC by catherinemeadows

Modified the Scaling Example NF to assign spawned children with the same service ID as the parent and updated the README with more detail about callback and advanced rings modes. 

- addressed issue [250](https://github.com/sdnfv/openNetVM/issues/250)

## Summary:

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          | [250](https://github.com/sdnfv/openNetVM/issues/250)
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [X] PR is ready for review

## Test Plan:
- tested NF in a chain (speed tester -> scaling -> basic monitor) to verify correct packet flow

2022-03-17 15:50 UTC, twood02 commented
@catherinemeadows 
Can you remind me -- Is the idea of this NF that it spawns N child NFs all with the same service ID as the "main" NF that started initially. Packets are then distributed across the `N+1` NFs.  All of these NFs then forward packets to whatever destination ID was set on the command line.

Is this right?  Or does the main NF not actually have a run loop so there are `N` nfs total receiving packets (only the children)?

2022-03-17 17:07 UTC, catherinemeadows commented
@twood02 Yes, the parent NF spawns N children NFs with the same service ID and the packets are distributed across the N+1 NFs and forwarded to the destination ID. Should I add this to the documentation?

2022-03-17 17:25 UTC, twood02 requested changes

2022-03-17 17:25 UTC, twood02 commented on examples/scaling_example/README.md
>  The NF will spawn X children (provided by `-n`, defaulting to 1 if arg isn't provided) and send packets to destination NF.
Revise this line with longer description of N+1 nfs

2022-03-17 17:25 UTC, twood02 commented on examples/scaling_example/README.md
> +./go.sh SERVICE_ID -d DST_ID [NUM_CHILDREN] [ADVANCED_RINGS]
does the `go` script hide the -n and -a arguments or is that needed here? Maybe this should be:

```
 ./go.sh SERVICE_ID -d DST_ID [-n NUM_CHILDREN] [-a]
```

2022-03-21 19:31 UTC, twood02 approved these changes
looks good to me

2022-03-21 19:32 UTC, twood02 commented
@NoahChinitzGWU can you build and run this code on one of your systems to verify it is working as expected?  Post a screenshot/paste the output here

2022-03-21 21:34 UTC, NoahChinitzGWU commented
Manager:
![Screenshot from 2022-03-21 17-32-06](https://user-images.githubusercontent.com/62520433/159367328-90e88272-c676-4d20-ae58-4489c2fa07ff.png)

Scaling NF Left Terminal, Monitor NF Right Terminal:
![Screenshot from 2022-03-21 17-32-30](https://user-images.githubusercontent.com/62520433/159367426-48096cc9-4f2e-4c2c-9902-059750babb71.png)

Does this seem correct, or should I be seeing 3 additional scaling NFs in the manager?

2022-03-21 21:37 UTC, catherinemeadows commented
They should scale once you send packets to it (you can use speed tester)

2022-03-21 21:44 UTC, NoahChinitzGWU commented
Manager:
![Screenshot from 2022-03-21 17-44-17](https://user-images.githubusercontent.com/62520433/159368681-a6a5daef-de8b-4b4b-9e4a-c739989242b9.png)

Works!

2022-03-21 21:45 UTC, NoahChinitzGWU commented
![Screenshot from 2022-03-21 17-45-01](https://user-images.githubusercontent.com/62520433/159368774-7b252113-10b6-495f-90e1-06cb8e1fd9f8.png)

NFs used

2022-03-21 21:48 UTC, NoahChinitzGWU approved these changes
See my previous comments for screenshots of working output

2022-03-21 23:25 UTC, twood02 commented
@dennisafa - can you do a very quick review and approve this if nothing jumps out at you?

2022-03-22 18:03 UTC, dennisafa approved these changes
Changes look good to me. Unrelated to the bug itself, I think it would make sense to do the scaling differently. Right now, we spawn the child NF's as soon as we receive a packet in the packet_handler_with_scaling() function. The new NF's packet handler is then set to packet_handler_fwd(). Why not spawn all of the child NF's upon startup, rather than wait for the first packet? The current implementation would make more sense if we were spawning the child NF's based on say, the packet count/rate.

2022-03-28 15:42 UTC, merged