Weighted
sdnfv/openNetVM pull request #327
Opened 2022-07-26 14:28 UTC by xwedea

<<Replace this line with a short description of the changes>>

## Summary:

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review

## Test Plan:

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

2022-07-31 12:06 UTC, xwedea commented
@twood02 we allocate and free lb->weights and lb->policy using standard malloc and free functions. However, in the previous of the code dpdk's function rte_calloc and rte_free are used. Should I edit this code to use those functions? I am not sure how to free them later in that case.

2022-08-01 17:02 UTC, twood02 requested changes
Good start! I've marked a few things which can be improved.

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                ret = fscanf(cfg, "%s %s %d", ip, mac, &weight);
does this require that the config files for all policies have a weight field even if it isn't being used? If I'm using a simple round robin policy I shouldn't have to put weights in my config file.

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                if (strcmp(policy, "weighted_random")) weight = 1;
This looks wrong. Why ignore the weights with this policy?

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +        if (!strcmp(lb->policy,"random")) {
string comparisons are slow, so we want to avoid them in the "data path" of our functions. Instead you should make lb->policy an int and use #declare statements to list out the possible options or use enums.

Then I would make this all a switch statement instead of if/elseif/else.

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                srand((unsigned) time(&t));
you only need to initialize the random number generator once. Put this in a setup function instead of here

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +        }
what happens if you don't match any of the above policies? Set your switch statement up to handle that.

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                srand((unsigned) time(&t));
```suggestion
```
only needs to be done once at startup

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +
looks like indentation is wrong here

2022-08-01 17:02 UTC, twood02 commented on run_manager.sh
> +./onvm/go.sh -k 3 -n 0xFF -s stdout
remove this file since it is specific to your cloudlab setup and isn't really part of the NF

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +        char *policy;
as mentioned below, make this an int or enum

2022-08-01 17:02 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +        int total_weight;
your data structure here will allow us to represent weighted load balancers, but there could be other policies we could come up with in the future that might need totally different data. For now this is fine, but you should think about how you would make this data structure generic so it works for all LBs (but still allows customization by each policy in some way)

2022-08-01 17:07 UTC, twood02 commented
> @twood02 we allocate and free lb->weights and lb->policy using standard malloc and free functions. However, in the previous of the code dpdk's function rte_calloc and rte_free are used. Should I edit this code to use those functions? I am not sure how to free them later in that case.

The main differences between normal malloc and rte_malloc are:

- `rte_malloc` allocates memory in the DPDK shared memory pool. This allows all NFs and the manager to access the data. That can either be a good thing or a bad thing
- `rte_malloc` is much faster than `malloc` if you are frequently allocating and freeing objects (if you want to understand why, [read about DPDK memory allocation and pools here](https://www.dpdk.org/blog/2019/08/21/memory-in-dpdk-part-1-general-concepts/#inpage-nav-6))

For your use case, you are allocating memory which will only be used by the LB NF and you are only doing it once when the NF starts. So it is fine to use normal malloc here.

2022-08-02 08:25 UTC, xwedea commented on examples/load_balancer/load_balancer.c
> +                ret = fscanf(cfg, "%s %s %d", ip, mac, &weight);
yes, it requires that the server.conf have weights at the end of each line. We tried to keep it as simple as possible, as this part is going to be replaced with a json parser that @andreaseno is working on.

2022-08-02 08:36 UTC, xwedea commented on examples/load_balancer/load_balancer.c
> +                if (strcmp(policy, "weighted_random")) weight = 1;
we set weights to 1, if policy is not weighted random. strcmp syntax is unintuitive

2022-08-02 08:47 UTC, xwedea commented on examples/load_balancer/load_balancer.c
> +        }
at line 281, it checks validity of the specified policy, when parsing. Should I do an additional check here as well?

`
if (!((!strcmp(lb->policy,"random")) || (!strcmp(lb->policy,"rrobin")) || (!strcmp(lb->policy,"weighted_random")))) {
                rte_exit(EXIT_FAILURE, "Invalid policy. Check server.conf\n");
        }
`

2022-08-02 11:02 UTC, xwedea commented on examples/load_balancer/load_balancer.c
> +                srand((unsigned) time(&t));
I put it in main, as the existing setup functions have a specific name & task to do. If you wish, I can put it in one of the parsers, or define a new setup function to handle this type of general setup tasks.

2022-08-02 11:55 UTC, xwedea commented on examples/load_balancer/load_balancer.c
> +        }
I updated this part in the "enumerate lb->policy" commit

I do a validity check both when parsing and adding entries to table:

line 282 (parsing)
```
if (!strcmp(config_policy, "rrobin")) lb->policy = rrobin;
else if (!strcmp(config_policy, "random")) lb->policy = random;
else if (!strcmp(config_policy, "weighted_random")) lb->policy = weighted_random;
else rte_exit(EXIT_FAILURE, "Invalid policy. Check server.conf\n");
```
line 492 (adding entries to table)
```
switch (lb->policy)
        {
        case random:
                data->dest = rand() % lb->server_count;
                break;
        case rrobin:
                data->dest = lb->num_stored % lb->server_count;
                break;
        case weighted_random:
                int i, wrand, cur_weight_sum;
                wrand = rand() % lb->total_weight;
                cur_weight_sum=0;
                for (i = 0; i < lb->server_count; i++) {
                        cur_weight_sum+=lb->weights[i];
                        if(wrand < cur_weight_sum) {
                                data->dest=i;
                                break;
                        }
                }
                break;
        default:
                rte_exit(EXIT_FAILURE, "Invalid policy while adding entry to table!\n");
                break;
        }
```

2022-08-02 13:21 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                if (strcmp(policy, "weighted_random")) weight = 1;
ah that's right. This will be clearer if you switch to the enum values since they are defined by this point.

2022-08-02 13:22 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +                ret = fscanf(cfg, "%s %s %d", ip, mac, &weight);
ok, let's be sure that the json PR does this in a flexible way that doesn't require weight to be defined for policies that don't need it. @andreaseno

2022-08-03 15:23 UTC, twood02 requested changes
a bit more cleanup then this is ready

2022-08-03 15:23 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +
@xwedea remove all dead (commented out) code

2022-08-03 15:23 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +        // free(lb->policy);
```suggestion
```

2022-08-03 15:23 UTC, twood02 commented on examples/load_balancer/load_balancer.c
> +
(here and elsewhere)

2022-08-04 16:56 UTC, andreaseno commented on examples/load_balancer/load_balancer.c
> +                ret = fscanf(cfg, "%s %s %d", ip, mac, &weight);
@twood02 I have built the json parser so that it only throws an error for missing weights when the policy is "weighted_random"

2022-08-04 17:51 UTC, xwedea commented
@twood02 I removed the commented code and did a final check with all policies. this should be good to go

2022-08-04 18:29 UTC, twood02 commented
@xwedea - can you put a description of what this PR adds at the top of this page. When we make our release notes for each ONVM version we go back to the PRs to get short descriptions of each new feature.

Otherwise this looks good and I will merge it into develop.  Then next week we'll go through a full review process with @andreaseno's PR where he will run the NFs and demonstrate it working for me.

2022-08-04 18:32 UTC, twood02 approved these changes
Looks good! 

The only issue is that it requires all config files to have weights specified even if they aren't used, but this will be resolved by PR #328 that changes to using JSON config files.

2022-08-04 19:10 UTC, xwedea commented
@twood02 I put a description.

2022-08-04 19:12 UTC, merged